services:
  # Nginx Reverse Proxy (The Gateway)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
    restart: always

  # Backend Service
  server:
    build: ./server
    container_name: hostel-server
    expose:
      - "5000"
    env_file:
      - ./server/.env
    environment:
      - PORT=5000
      - NODE_ENV=production
    restart: always

  # Frontend Service
  client:
    build:
      context: ./client
      args:
        # Now pointing to Nginx (Port 80) /api
        - VITE_API_URL=/api
    container_name: hostel-client
    expose:
      - "5173"
    depends_on:
      - server
    restart: always
